### ISSUE TITLE
Display Full 3 Entries of English Subs

### ISSUE THREAD

**Issue by ishunyu** [ishunyu/magpie-dict#3]

**Comment by ishunyu** [comment]
Carsen: I still noticed some results that are missing a few lines. Is it possible to force the dictionary to display 3 entires of English subs
![75833CE9-3F72-4935-AF9C-3B7DF777EBF7](https://user-images.githubusercontent.com/1459666/87216238-abe4e380-c2f2-11ea-8c70-3dd0cc77891c.png)

**Comment by ishunyu** [comment]
Search word: 生疏

**Comment by ishunyu** [comment]
@CarsenWei the data is here, https://github.com/ishunyu/magpie-dict/blob/master/resource/data/zhz/data/12.csv, seems like it was kind of hard for the script to match up the lines.

**Comment by CarsenWei** [comment]
I tried the search word 方舱 for China Now and some results also only showed only one line of English.

**Comment by ishunyu** [comment]
@CarsenWei I think it's because the timing in the Chinese sub vs the timing in English sub are too far off, if you look around line 742 in this file (https://github.com/ishunyu/magpie-dict/blob/master/resource/data/cn/data/46.csv), the script made a good effort to try to line up the subtitles (There are many more Chinese lines than English lines).

Maybe we can expand the number of lines if either the Chinese or English has less than 2 lines subs.

**Comment by ishunyu** [comment]
#19
